export const PLACE_TYPE_OPTIONS = [
  'Artefacts / Scatter',
  'BP Dating Details',
  'Birthplace',
  'Burial',
  'Camp',
  'Creation / Dreaming Narrative',
  'Engraving',
  'Fish Trap',
  'Grinding areas / Grooves',
  'Historical',
  'Hunting Place',
  'Landscape / Seascape Feature',
  'Massacre',
  'Meeting Place',
  'Midden',
  'Mission',
  'Modified Tree',
  'Ochre',
  'Painting',
  'Plant Resource',
  'Quarry',
  'Repository / Storage Place',
  'Ritual / Ceremonial',
  'Rock Shelter',
  'Shell',
  'Stone Arrangement',
  'Sub surface cultural material',
  'Traditional Structure',
  'Water Source',
  'Other',
] as const

export type PlaceTypeOption = (typeof PLACE_TYPE_OPTIONS)[number]
